inherit_from: .rubocop_todo.yml

# Use plugin syntax per RuboCop plugin migration guide
plugins:
  - rubocop-rails
  - rubocop-rspec

# Global settings
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'lib/tasks/**/*'

# Common project tweaks to avoid noisy false-positives while keeping code tidy
Layout/LineLength:
  Max: 160
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/admin/dashboard_controller.rb'
    - 'app/controllers/admin/sale_orders_controller.rb'
    - 'app/controllers/api/v1/**/*'
    - 'app/helpers/seo_helper.rb'
    - 'app/helpers/products_helper.rb'
    - 'app/helpers/meta_tags_helper.rb'
    - 'app/models/inventory.rb'
    - 'app/models/sale_order_item.rb'
    - 'app/services/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'Rakefile'
    - 'app/controllers/**/*'
    - 'app/services/**/*'
    - 'db/seeds.rb'

# Controllers/services often exceed default thresholds during orchestration
Metrics/MethodLength:
  Max: 80
  Exclude:
    - 'app/controllers/**/*'
    - 'app/services/**/*'
    - 'db/seeds.rb'
Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'app/services/**/*'
    - 'db/seeds.rb'
Metrics/PerceivedComplexity:
  Max: 14
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'app/services/**/*'
Metrics/CyclomaticComplexity:
  Max: 14
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'app/services/**/*'
Metrics/ClassLength:
  Max: 280
  Exclude:
    - 'app/controllers/**/*'
    - 'app/services/**/*'
Metrics/ModuleLength:
  Max: 220
Metrics/ParameterLists:
  Exclude:
    - 'app/services/**/*'
    - 'app/helpers/**/*'

# Rails cops that are too noisy for bulk update patterns
Rails/SkipsModelValidations:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false

# Lint cops relaxed for legacy code
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/controllers/admin/dashboard_controller.rb'
    - 'app/services/**/*'
Lint/DuplicateBranch:
  Enabled: false
Lint/SuppressedException:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/services/**/*'
    - 'app/helpers/**/*'
Lint/FloatComparison:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'db/seeds.rb'
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Naming
Naming/MethodParameterName:
  MinNameLength: 1
Naming/AccessorMethodName:
  Enabled: false

# Style cops
Style/FormatStringToken:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/HashSyntax:
  Enabled: false

# Rails cops
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/DangerousColumnNames:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/AfterCommitOverride:
  Enabled: false
Rails/WhereNotWithMultipleConditions:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/ComparableClamp:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/services/**/*'
    - 'spec/models/**/*'
    - 'spec/requests/**/*'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/services/**/*'
    - 'spec/models/**/*'
    - 'spec/requests/**/*'
RSpec/ContextWording:
  Enabled: false
Lint/Debugger:
  Exclude:
    - 'spec/rails_helper.rb'

Rails/I18nLocaleTexts:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/services/**/*'
    - 'app/models/**/*'
    - 'spec/**/*'
