name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [ main, perf/image-optimization ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - name: Install system deps (chromium & vips)
        run: sudo apt-get update && sudo apt-get install -y chromium-browser libvips

      - name: Install gems
        run: bundle install --without development test || true

      - name: Precompile assets
        run: RAILS_ENV=production bundle exec rails assets:precompile

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        run: npm install

      - name: Run Lighthouse CI
        env:
          CHROME_PATH: /usr/bin/chromium-browser
            LH_PRODUCT_PATH: "/products/placeholder-slug"
        run: npm run lhci || (echo 'Lighthouse failed' && exit 1)

      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lighthouse-report
